name: prestmit_app

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-15.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: ^2.2.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    
  # fonts:
  #   - family: Trueno
  #     fonts:
  #       - asset: assets/fonts/trueno/TruenoBd.otf
  #       - asset: assets/fonts/trueno/TruenoBdIt.otf
  #       - asset: assets/fonts/trueno/TruenoBdOl.otf
  #       - asset: assets/fonts/trueno/TruenoBdOlIt.otf
  #       - asset: assets/fonts/trueno/TruenoBlk.otf
  #       - asset: assets/fonts/trueno/TruenoBlkIt.otf
  #       - asset: assets/fonts/trueno/TruenoBlkOl.otf
  #       - asset: assets/fonts/trueno/TruenoBlkOlIt.otf
  #       - asset: assets/fonts/trueno/TruenoExBd.otf
  #       - asset: assets/fonts/trueno/TruenoExBdIt.otf
  #       - asset: assets/fonts/trueno/TruenoExBdOl.otf
  #       - asset: assets/fonts/trueno/TruenoExBdOlIt.otf
  #       - asset: assets/fonts/trueno/TruenoLt.otf
  #       - asset: assets/fonts/trueno/TruenoLtIt.otf
  #       - asset: assets/fonts/trueno/TruenoRg.otf
  #       - asset: assets/fonts/trueno/TruenoRgIt.otf
  #       - asset: assets/fonts/trueno/TruenoSBd.otf
  #       - asset: assets/fonts/trueno/TruenoSBdIt.otf
  #       - asset: assets/fonts/trueno/TruenoUltBlk.otf
  #       - asset: assets/fonts/trueno/TruenoUltBlkIt.otf
  #       - asset: assets/fonts/trueno/TruenoUltLt.otf
  #       - asset: assets/fonts/trueno/TruenoUltLtIt.otf
  #   - family: ActionSans
  #     fonts:
  #       - asset: assets/fonts/action-sans/ActionSans-Bold.otf
  #       - asset: assets/fonts/action-sans/ActionSans-Light.otf
  #       - asset: assets/fonts/action-sans/ActionSans-Medium.otf
  #       - asset: assets/fonts/action-sans/ActionSans-Regular.otf
